behaviors:
  AmrAgent:
    trainer_type: poca
    hyperparameters:
      batch_size: 512
      buffer_size: 5120
      learning_rate: 0.0000005
      beta: 0.00005 #  With decay = learning_rate_schedule
      epsilon: 0.005 #  With decay = learning_rate_schedule
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      # curiosity:
      #   gamma: 0.99
      #   strength: 0.02
      #   network_settings:
      #     hidden_units: 256
      #   learning_rate: 0.0003
    keep_checkpoints: 15
    checkpoint_interval: 1000000
    max_steps: 24000000
    time_horizon: 128
    summary_freq: 250000
environment_parameters:
  HospitalSize:
    curriculum:
      - name: SmallHospital # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: AmrAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 1
        value: 5.0