behaviors:
  AmrAgent:
    trainer_type: poca
    hyperparameters:
      batch_size: 128
      buffer_size: 2048
      learning_rate: 0.0007
      beta: 0.005 #  With decay = learning_rate_schedule
      epsilon: 0.2 #  With decay = learning_rate_schedule
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
    keep_checkpoints: 5
    checkpoint_interval: 500000
    max_steps: 49000000
    time_horizon: 128
    summary_freq: 40000
environment_parameters:
  HospitalSize:
    curriculum:
      - name: PairRoom # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: AmrAgent
          signal_smoothing: true
          min_lesson_length: 500
          threshold: 0.1
        value: 1.0
      - name: SmallHospital # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: AmrAgent
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.3
        value: 2.0
      - name: MediumHospital # This is the start of the third lesson
        completion_criteria:
          measure: progress
          behavior: AmrAgent
          signal_smoothing: true
          min_lesson_length: 300
          threshold: 0.5
        value: 3.0
      - name: BigHospital # This is the start of the fourth lesson
        value: 4.0
