behaviors:
  AmrAgent:
    trainer_type: poca
    hyperparameters:
      batch_size: 1024
      buffer_size: 10240
      learning_rate: 0.00008
      beta: 0.01 #  With decay = learning_rate_schedule
      epsilon: 0.2 #  With decay = learning_rate_schedule
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: constant
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 3
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.99
        strength: 1.0
      # curiosity:
      #   gamma: 0.99
      #   strength: 0.02
      #   network_settings:
      #     hidden_units: 256
      #   learning_rate: 0.0003
    keep_checkpoints: 5
    checkpoint_interval: 1000000
    max_steps: 62500000
    time_horizon: 128
    summary_freq: 500000
environment_parameters:
  HospitalSize:
    curriculum:
      - name: SingleRoom # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: AmrAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.025
        value: 1.0
      - name: BigSingleRoom # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: AmrAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.20
        value: 2.0
      - name: PairRoom # The '-' is important as this is a list
        completion_criteria:
          measure: progress
          behavior: AmrAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.35
        value: 3.0
      - name: SmallHospital # This is the start of the second lesson
        completion_criteria:
          measure: progress
          behavior: AmrAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.6
        value: 4.0
      - name: MediumHospital # This is the start of the third lesson
        completion_criteria:
          measure: progress
          behavior: AmrAgent
          signal_smoothing: true
          min_lesson_length: 100
          threshold: 0.8
        value: 5.0
      - name: BigHospital # This is the start of the fourth lesson
        value: 6.0